### ISSUE TITLE
color misalignment with nanocams + cam500b + nanopi s2

### ISSUE THREAD

**Issue by vinmicgra** [friendlyarm/nexell_linux_platform#7]
Setup: nanopi S2, cam500b, latest debian image.

Command "nanocams -o camtest.jpg -c 3" creates images like below. Images have very low saturation and colors seem to be misaligned. Would be great if somebody could give a hint.

![bildschirmfoto 2017-08-18 um 03 52 31](https://user-images.githubusercontent.com/1365395/29441133-5d504c98-83c9-11e7-8885-da61cbd2e5d9.png)

best regards, vincent.

**Comment by friendlyarm** [comment]
We tested it again and found this issue. This issue was introduced by a patch (03bc3af) we made for 6818 SoC. The preview function should work normally. We will fix this issue soon (in our next released image).
You can try the following commands to get nanocams which only work for 4418 and don't have this issue:
    git clone https://github.com/friendlyarm/nexell_linux_platform.git
    cd nexell_linux_platform
    git checkout -B s5p4418 32ea15f
    make

Thanks for pointing this out.

**Comment by vinmicgra** [comment]
Thank you very much. Image quality is much better with 32ea15f. 
I had to use the makefile from the latest branch because of compiling issues. But now image quality is very good.
